# Generated by Django 5.2.3 on 2025-07-01 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0002_llmanalysisrecord"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LLMAnalysisRecord",
        ),
    ]
