# Generated by Django 5.2.3 on 2025-07-01 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0002_add_user_auth"),
        ("detection", "0003_delete_llmanalysisrecord"),
    ]

    operations = []
