# Generated by Django 5.2.3 on 2025-07-01 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0004_merge_20250701_2342"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="loginattempt",
            new_name="detection_l_usernam_27b248_idx",
            old_name="detection_l_usernam_b8e5a5_idx",
        ),
        migrations.RenameIndex(
            model_name="loginattempt",
            new_name="detection_l_success_bb646e_idx",
            old_name="detection_l_success_8b7c8a_idx",
        ),
    ]
